# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

permalink: pretty
source: docs
baseurl: "/device-api"

sass:
  sass_dir: ../
  style: compressed

github:
  repo: https://github.com/aisuhua/device-api
